<a href="https://colab.research.google.com/github/gullyboy007/deep-learn/blob/master/TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
a = tf.constant(5)
b = tf.constant(10)

c = a + b


In [21]:
with tf.Session() as sess:


  output = sess.run(c)
  print(output)




15


In [22]:
tf.InteractiveSession()
c.eval()

15

In [24]:
x = 2
y = 5

#here we see how graphs work

op1 = tf.add(x,y)
op2 = tf.multiply(x,y)
op3 = tf.pow(op2,op1)

with tf.Session() as sess:
  op3 = sess.run(op3)
  print(op3)


10000000


In [25]:
#constants = fixed value tensors-not trainable
#variables = tensors initilized in a session-trainable
#placeholders = tensors whose values are unknown during construction but as input during a session

#CONSTANT

import numpy as np

a = tf.constant(3)
b = tf.constant(5)
c = a+b

tf.InteractiveSession()
print(c.eval())




8


/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [27]:
#Variable

a = tf.Variable(0)
b = tf.constant(1)

mid = tf.add(a,b)
final = tf.assign(a, mid)
var = tf.initialize_all_variables()

with tf.Session() as sess:
  sess.run(var)

  for i in range(3):
    sess.run(final)
    print(sess.run(a))  



1
2
3


In [28]:
x = tf.placeholder("float32", None)
y = x**2

with tf.Session() as sess:
  result = sess.run(y, feed_dict = {x : [1,2,3]})
  print(result)

[1. 4. 9.]


In [30]:
x = tf.placeholder("float32", [None,3])
y = x**2

with tf.Session() as sess:
  result = sess.run(y, feed_dict = {x : [[1,2,3],[4,5,6]]})
  print(result)

[[ 1.  4.  9.]
 [16. 25. 36.]]
